# Generated by Django 5.2.6 on 2026-07-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
