# Generated by Django 6.0.5 on 2026-07-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_patient_email_verification_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="password_reset_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="password_reset_token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
