# Generated by Django 5.2.6 on 2026-07-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_patient_email_verification_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_type", models.CharField(max_length=100, unique=True)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="NotificationEmailSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("transport", models.CharField(default="smtp", max_length=20)),
                ("from_email", models.EmailField(blank=True, max_length=254)),
                ("from_name", models.CharField(blank=True, max_length=255)),
                ("reply_to", models.EmailField(blank=True, max_length=254)),
                ("smtp_host", models.CharField(blank=True, max_length=255)),
                ("smtp_port", models.PositiveIntegerField(default=587)),
                ("smtp_use_tls", models.BooleanField(default=True)),
                ("smtp_username", models.CharField(blank=True, max_length=255)),
                (
                    "smtp_password_encrypted",
                    models.CharField(blank=True, max_length=512),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
